
# Arrays
teamMembers = ["Parker Phelps - Product Owner", "Christian Fortin - Scrum Master", "Matthew Burrus - Program Analyst", "Jessica Weeks - QA Developer", "Destan Hutcherson - Program Analyst", "Flora Cherotich - Database Technician", "Adia Chue - Web Developer"]

# This is used to store certain values and make use of them later
currentEmployeeID = []
currentUserID = []
currentUsername = []
