
# Arrays
teamMembers = ["Parker Phelps - Product Owner", "Christian Fortin - Scrum Master", "Matthew Burrus - Program Analyst", "Jessica Weeks - QA Developer", "Destan Hutcherson - Program Analyst", "Flora Cherotich - Database Technician", "Adia Chue - Web Developer"]

# This is used to store certain values and make use of them later
currentEmployeeID = []
currentUserID = []
currentUsername = ["Test"]

isPhysician = [False]

customTime = [False]

prevWindowCoords = [0, 0]

validPatientFN_SA = [False]
validPatientLN_SA = [False]
validPatientDOB_SA = [False]
validOfficeLocation_SA = [False]
validAppointmentReason_SA = [False]
validAppointmentType_SA = [False]
validPhysicianName_SA = [False]
validAppointmentDate_SA = [False]

validOfficeLocation_RA = [False]
validPhysicianName_RA = [False]
validAppointmentDate_RA = [False]
validRescheduleDate_RA = [False]

validOfficeLocation_CA = [False]
validPhysicianName_CA = [False]
validAppointmentDate_CA = [False]
